# Generated by Django 5.1.4 on 2025-01-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='duration',
        ),
        migrations.AddField(
            model_name='travelplan',
            name='traveldays',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
    ]
