# Generated by Django 5.1.4 on 2025-01-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_remove_travelplan_duration_travelplan_traveldays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
