# Generated by Django 5.1.4 on 2025-01-14 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0006_alter_customuser_birthdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destinations",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
