# Generated by Django 5.1.4 on 2025-01-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0007_destination_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="destination",
            name="image",
            field=models.ImageField(default="null", upload_to="destinations/"),
        ),
    ]
